#!/usr/bin/env sh

# after doing git clone https://github.com/j624364/dotfiles.git
cd ~/dotfiles
git submodule update --init --recursive

sudo pacman -S zsh --noconfirm
# then install oh-my-zsh also
# (link may not work in the future)
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

sudo pacman -S neovim kitty stow --noconfirm

# remove .zshrc generated by oh-my-zsh
# at ~/dotfiles
stow .

# create repos dir
cd ~
mkdir Repos

# install dwm
cd ~/Repos
git clone https://github.com/j624364/dwm.git
cd dwm
make && make install && sudo make install
sudo pacman -S network-manager-applet flameshot picom redshift nitrogen sxhkd rofi xorg-xsetroot --noconfirm

# setup programming compilers & lsps
sudo pacman -S npm gopls ghc haskell-language-server
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

cargo install cargo-leptos --locked

sudo pacman -S bpytop
cargo install bat loc

# now go clone repos, etc
sudo pacman -S cronie --noconfirm
# you may want to set up crontabs now
# crontab -e

sudo pacman -S spotify-launcher --noconfirm

# set wallpaper with gui
nitrogen
